
spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:h2:mem:thiru1
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: none
    
server:
  port: 8082
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
     hostname: localhost