spring:  application:    name: subject-serviceserver:  port: 8091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    # below is the eureka server url      default-zone: http://localhost:8761/eureka
  instance:    hostname: localhost     